// apps/vitepress/.vitepress/theme/components/PostCard.vue
<script setup lang="ts">
// Ported from apps/kudzu/src/components/PostCard.tsx — same `.row`/`.thumb`/
// `.title`/`.date` markup and class names.
import type { PostCardData } from "../lib/types";

const { post } = defineProps<{ post: PostCardData }>();
const dateLabel = post.date ? new Intl.DateTimeFormat("ko-KR").format(new Date(post.date)) : null;
</script>

<template>
  <a class="row" :href="post.href">
    <span class="thumb">
      <img v-if="post.coverUrl" :src="post.coverUrl" alt="" loading="lazy" />
      <template v-else>thumbnail</template>
    </span>
    <span class="title">{{ post.title }}</span>
    <span v-if="dateLabel" class="date">{{ dateLabel }}</span>
  </a>
</template>

// apps/react-router/app/components/PostCard.tsx
import { Link } from "react-router";
import styles from "../styles/post.module.css";

export interface PostCardData {
  id: string;
  title: string;
  date: string | null;
  coverUrl: string | null;
}

export default function PostCard({ post }: { post: PostCardData }) {
  const dateLabel = post.date
    ? new Intl.DateTimeFormat("ko-KR").format(new Date(post.date))
    : null;

  return (
    <Link to={`/news/post/${post.id}`} className={styles.row}>
      <span className={styles.thumb}>
        {post.coverUrl ? (
          <img src={post.coverUrl} alt="" loading="lazy" />
        ) : (
          "thumbnail"
        )}
      </span>
      <span className={styles.title}>{post.title}</span>
      {dateLabel && <span className={styles.date}>{dateLabel}</span>}
    </Link>
  );
}
