// apps/react-router/app/components/Header.tsx
import { Link } from "react-router";
import styles from "../styles/header.module.css";

export default function Header() {
  return (
    <header className={styles.header}>
      <div className={styles.container}>
        <Link to="/" className={styles.logo}>
          OTW <span className={styles.logoSub}>for</span> FE
        </Link>
        <Link to="/news/list/1" className={styles.link}>
          Archive
        </Link>
      </div>
    </header>
  );
}

// apps/vitepress/.vitepress/theme/components/Header.vue
<script setup lang="ts">
import { BASE } from "../lib/site";
</script>

<template>
  <header class="header">
    <div class="container">
      <a class="logo" :href="`${BASE}/`">
        OTW <span class="logo-sub">for</span> FE
      </a>
      <a class="link" :href="`${BASE}/news/list/1`">Archive</a>
    </div>
  </header>
</template>
