// apps/docusaurus/src/components/PostCard.tsx
import React from "react";

export interface PostCardData {
  id: string;
  title: string;
  date: string | null;
  coverUrl: string | null;
}

// Ported from apps/kudzu/src/components/PostCard.tsx (markup/classes kept
// identical). Unlike kudzu, the href is computed by the caller via
// `useBaseUrl()` and passed in as a prop, since hooks may only be called
// from function components/hooks, not from plain helper props objects.
export default function PostCard({
  post,
  href
}: {
  post: PostCardData;
  href: string;
}): React.ReactElement {
  const dateLabel = post.date
    ? new Intl.DateTimeFormat("ko-KR").format(new Date(post.date))
    : null;

  return (
    <a className="row" href={href}>
      <span className="thumb">
        {post.coverUrl ? <img src={post.coverUrl} alt="" loading="lazy" /> : "thumbnail"}
      </span>
      <span className="title">{post.title}</span>
      {dateLabel && <span className="date">{dateLabel}</span>}
    </a>
  );
}

// apps/vitepress/.vitepress/theme/components/PostCard.vue
<script setup lang="ts">
// Ported from apps/kudzu/src/components/PostCard.tsx — same `.row`/`.thumb`/
// `.title`/`.date` markup and class names.
import type { PostCardData } from "../lib/types";

const { post } = defineProps<{ post: PostCardData }>();
const dateLabel = post.date ? new Intl.DateTimeFormat("ko-KR").format(new Date(post.date)) : null;
</script>

<template>
  <a class="row" :href="post.href">
    <span class="thumb">
      <img v-if="post.coverUrl" :src="post.coverUrl" alt="" loading="lazy" />
      <template v-else>thumbnail</template>
    </span>
    <span class="title">{{ post.title }}</span>
    <span v-if="dateLabel" class="date">{{ dateLabel }}</span>
  </a>
</template>
